# SwiftLint Configuration for Hello Tetris iOS Project

# Disable rules that are too strict for this project
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - large_tuple
  - unused_import
  - unused_private_declaration

# Opt-in rules that are useful for this project
opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - vertical_whitespace

# Custom rule configurations
line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

# Exclude certain files/directories
excluded:
  - Pods
  - Carthage
  - build
  - DerivedData
  - .build
  - hellotetrisTests
  - hellotetrisUITests

# Custom rules for this project
custom_rules:
  no_hardcoded_strings:
    name: "No Hardcoded Strings"
    regex: '"[^"]*"'
    message: "Avoid hardcoded strings, use NSLocalizedString instead"
    severity: warning
    match_kinds:
      - string_literal

# Reporter configuration
reporter: "github-actions-logging" 