# SwiftLint Configuration for HelloTetris

# Basic rules for clean Swift code
opt_in_rules:
  - empty_count
  - trailing_newline
  - comma_inheritance
  - unused_import

disabled_rules:
  - trailing_whitespace # Allow some flexibility for generated files
  - line_length # SpriteKit nodes can have long method chains

# Include/exclude patterns
included:
  - hellotetris/
  - hellotetrisTests/

excluded:
  - build/
  - .build/
  - DerivedData/
  - hellotetris.xcodeproj/
  - "*.generated.swift"

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1500 # GameScene.swift is large due to complete Tetris implementation

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3

# Custom reporter for GitHub Actions
reporter: "github-actions-logging"
