# SwiftLint Configuration for HelloTetris Game

# Basic rules for clean Swift code
opt_in_rules:
  - empty_count
  - comma_inheritance

disabled_rules:
  - trailing_whitespace # Allow some flexibility for generated files
  - line_length # SpriteKit nodes can have long method chains
  - identifier_name # Allow short names like x, y for coordinates
  - type_name # Allow lowercase test class names
  - redundant_discardable_let # Common in test code
  - for_where # Sometimes if inside for is clearer
  - control_statement # Allow parentheses for clarity
  - implicit_getter # Explicit get can be clearer
  - redundant_sendable # Actor isolation is new, allow redundancy
  - unneeded_synthesized_initializer # Sometimes explicit is better
  - vertical_whitespace # Allow some flexibility in spacing
  - trailing_newline # File ending consistency not critical for game development

# Include/exclude patterns
included:
  - hellotetris/
  - hellotetrisTests/

excluded:
  - build/
  - .build/
  - DerivedData/
  - hellotetris.xcodeproj/
  - "*.generated.swift"

# Rule configurations
function_body_length:
  warning: 80
  error: 150

type_body_length:
  warning: 400
  error: 800 # GameEngine is complex

file_length:
  warning: 800
  error: 2000 # GameScene.swift is large due to complete Tetris implementation

large_tuple:
  warning: 4
  error: 5

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
    error: 4

# Custom reporter for GitHub Actions
reporter: "github-actions-logging"
