name: iOS 26 CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build iOS 26 App
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode 26 Beta
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.0-beta.3'
        
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Show Swift version
      run: swift --version
      
    - name: Build project
      run: |
        xcodebuild clean build \
          -project hellotetris.xcodeproj \
          -scheme hellotetris \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          SWIFT_VERSION=6.0
          
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/
        
  test:
    name: Test iOS 26 App
    runs-on: macos-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode 26 Beta
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.0-beta.3'
        
    - name: Run tests
      run: |
        xcodebuild test \
          -project hellotetris.xcodeproj \
          -scheme hellotetris \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          SWIFT_VERSION=6.0
          
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/
        
  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode 26 Beta
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.0-beta.3'
        
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: Run SwiftLint
      run: |
        swiftlint lint --reporter github-actions-logging
        
  security:
    name: Security Scan
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Security scan
      run: |
        echo "🔍 Running security checks..."
        
        # Check for hardcoded secrets (more intelligent)
        if grep -r "password.*=.*['\"].*['\"]\|secret.*=.*['\"].*['\"]\|token.*=.*['\"].*['\"]\|key.*=.*['\"].*['\"]" . --exclude-dir=.git --exclude-dir=build --exclude=*.md --exclude=*.storyboard --exclude=*.plist --exclude=*.xcconfig; then
          echo "⚠️  Potential hardcoded secrets found"
          exit 1
        fi
        
        # Check for debug code in production
        if grep -r "print(\|NSLog(\|debugPrint(\|fatalError(" . --exclude-dir=.git --exclude-dir=build --exclude=*.md --exclude=*.storyboard --exclude=*.plist; then
          echo "⚠️  Debug code found in production"
          exit 1
        fi
        
        echo "✅ Security scan completed"
        
  archive:
    name: Create Archive
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode 26 Beta
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.0-beta.3'
        
    - name: Create archive
      run: |
        xcodebuild archive \
          -project hellotetris.xcodeproj \
          -scheme hellotetris \
          -destination 'generic/platform=iOS' \
          -archivePath build/hellotetris.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          SWIFT_VERSION=6.0
          
    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: app-archive
        path: build/hellotetris.xcarchive 